"""add hidden_groups

Revision ID: 736da9b1cedb
Revises: d3f5a7b9c111
Create Date: 2026-09-12 16:29:16.738733
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "736da9b1cedb"
down_revision: str | None = "d3f5a7b9c111"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hidden_groups",
        sa.Column("provider", sa.String(length=16), nullable=False),
        sa.Column("external_group_id", sa.String(length=128), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("provider", "external_group_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hidden_groups")
    # ### end Alembic commands ###
