"""case archive fields

Revision ID: af66bc20f1ed
Revises: 736da9b1cedb
Create Date: 2026-09-14 22:50:46.527398
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af66bc20f1ed"
down_revision: str | None = "736da9b1cedb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cases", sa.Column("archived", sa.Boolean(), server_default="0", nullable=False))
    op.add_column("cases", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f("ix_cases_archived"), "cases", ["archived"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cases_archived"), table_name="cases")
    op.drop_column("cases", "archived_at")
    op.drop_column("cases", "archived")
    # ### end Alembic commands ###
